services:
  fastapi:
    build:
      context: .  # Builds the Dockerfile in the current directory
      dockerfile: Dockerfile # Make sure the Dockerfile is named correctly or just omit if it's the default 'Dockerfile'
    container_name: fastapi
    ports:
      - "8000:8000"
    restart: always
    networks:
      - docker-bridge # rename this to the bridge on your system
    volumes:
      - ./application.py:/app/application.py # Mounts the src directory into the container
      - ./requirements.txt:/app/requirements.txt # Mounts the requirements.txt file into the container
volumes:
  fastapi-data:
    driver: local
networks:
  docker-bridge: # rename this to the bridge on your system
    external: true