services:
  fastapi:
    build:
      context: .  # Builds the Dockerfile in the current directory
      dockerfile: Dockerfile # Make sure the Dockerfile is named correctly or just omit if it's the default 'Dockerfile'
    container_name: fastapi
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./src:/app/src # Mounts the src directory into the container
      - ./requirements.txt:/app/requirements.txt # Mounts the requirements.txt file into the container
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - redis-data:/data

volumes:
  fastapi-data:
    driver: local
  redis-data:
    driver: local
